import { Car } from "./schema";

export const carsList: Car[] = [
  {
    id: 1,
    make: "Tata",
    model: "Nexon",
    variant: "XZ Plus S",
    color: "Flame Red",
    price: 1450000,
    specs: {
      engine: "1.5L Turbo Diesel",
      transmission: "Automatic",
      fuelType: "Diesel",
      seatingCapacity: 5,
      topSpeed: 180,
      mileage: 24.5,
    },
    safetyRating: 0.92,
    userReviews: 4.6,
  },
  {
    id: 2,
    make: "Toyota",
    model: "Innova Crysta",
    variant: "GX 7STR",
    color: "White Pearl",
    price: 1950000,
    specs: {
      engine: "2.4L Diesel",
      transmission: "Manual",
      fuelType: "Diesel",
      seatingCapacity: 7,
      topSpeed: 165,
      mileage: 15.8,
    },
    safetyRating: 0.85,
    userReviews: 4.4,
  },
  {
    id: 3,
    make: "Honda",
    model: "City",
    variant: "VX CVT",
    color: "Meteoroid Grey",
    price: 1350000,
    specs: {
      engine: "1.5L i-VTEC Petrol",
      transmission: "Automatic",
      fuelType: "Petrol",
      seatingCapacity: 5,
      topSpeed: 195,
      mileage: 18.4,
    },
    safetyRating: 0.88,
    userReviews: 4.5,
  },
  {
    id: 4,
    make: "BMW",
    model: "3 Series",
    variant: "330i M Sport",
    color: "Alpine White",
    price: 6200000,
    specs: {
      engine: "2.0L TwinPower Turbo",
      transmission: "Automatic",
      fuelType: "Petrol",
      seatingCapacity: 5,
      topSpeed: 250,
      mileage: 14.2,
    },
    safetyRating: 0.95,
    userReviews: 4.7,
  },
  {
    id: 5,
    make: "Maruti",
    model: "Swift",
    variant: "ZXi+",
    color: "Metallic Blue",
    price: 950000,
    specs: {
      engine: "1.2L Z-Series Petrol",
      transmission: "Manual",
      fuelType: "Petrol",
      seatingCapacity: 5,
      topSpeed: 170,
      mileage: 24.8,
    },
    safetyRating: 0.78,
    userReviews: 4.3,
  },
  {
    id: 6,
    make: "Suzuki",
    model: "Vitara Brezza",
    variant: "ZXi DT",
    color: "Brave Khaki",
    price: 1250000,
    specs: {
      engine: "1.5L K15C Petrol",
      transmission: "Automatic",
      fuelType: "Petrol",
      seatingCapacity: 5,
      topSpeed: 175,
      mileage: 18.7,
    },
    safetyRating: 0.82,
    userReviews: 4.2,
  },
  {
    id: 7,
    make: "Volkswagen",
    model: "Tiguan",
    variant: "GT Plus",
    color: "Deep Black",
    price: 3850000,
    specs: {
      engine: "2.0L TSI Petrol",
      transmission: "Automatic",
      fuelType: "Petrol",
      seatingCapacity: 5,
      topSpeed: 220,
      mileage: 13.5,
    },
    safetyRating: 0.93,
    userReviews: 4.6,
  },
  {
    id: 8,
    make: "Tata",
    model: "Harrier",
    variant: "Fearless Pure+",
    color: "Oberon Black",
    price: 2100000,
    specs: {
      engine: "2.0L Kryotec Diesel",
      transmission: "Automatic",
      fuelType: "Diesel",
      seatingCapacity: 5,
      topSpeed: 190,
      mileage: 14.5,
    },
    safetyRating: 0.89,
    userReviews: 4.5,
  },
  {
    id: 9,
    make: "Toyota",
    model: "Camry",
    variant: "Hybrid",
    color: "Attitude Black",
    price: 4800000,
    specs: {
      engine: "2.5L Hybrid",
      transmission: "Automatic",
      fuelType: "Hybrid",
      seatingCapacity: 5,
      topSpeed: 210,
      mileage: 19.1,
    },
    safetyRating: 0.94,
    userReviews: 4.8,
  },
  {
    id: 10,
    make: "Honda",
    model: "CR-V",
    variant: "Hybrid RS",
    color: "Radiant Red",
    price: 5200000,
    specs: {
      engine: "2.0L Hybrid",
      transmission: "Automatic",
      fuelType: "Hybrid",
      seatingCapacity: 5,
      topSpeed: 200,
      mileage: 18.9,
    },
    safetyRating: 0.91,
    userReviews: 4.4,
  },
  {
    id: 11,
    make: "BMW",
    model: "X5",
    variant: "xDrive40i M Sport",
    color: "Carbon Black",
    price: 10500000,
    specs: {
      engine: "3.0L Mild Hybrid",
      transmission: "Automatic",
      fuelType: "Petrol",
      seatingCapacity: 5,
      topSpeed: 250,
      mileage: 11.8,
    },
    safetyRating: 0.96,
    userReviews: 4.7,
  },
  {
    id: 12,
    make: "Maruti",
    model: "Ertiga",
    variant: "ZXi+ CNG",
    color: "Pearl Arctic White",
    price: 1350000,
    specs: {
      engine: "1.5L CNG",
      transmission: "Manual",
      fuelType: "CNG",
      seatingCapacity: 7,
      topSpeed: 160,
      mileage: 26.1,
    },
    safetyRating: 0.81,
    userReviews: 4.3,
  },
  {
    id: 13,
    make: "Volkswagen",
    model: "Virtus",
    variant: "GT Plus",
    color: "Rising Blue",
    price: 1650000,
    specs: {
      engine: "1.5L TSI Petrol",
      transmission: "Automatic",
      fuelType: "Petrol",
      seatingCapacity: 5,
      topSpeed: 200,
      mileage: 18.2,
    },
    safetyRating: 0.87,
    userReviews: 4.5,
  },
  {
    id: 14,
    make: "Tata",
    model: "Curvv EV",
    variant: "Empowered+",
    color: "Virtual Sunrise",
    price: 2150000,
    specs: {
      engine: "Electric Motor",
      transmission: "Automatic",
      fuelType: "Electric",
      seatingCapacity: 5,
      topSpeed: 160,
      mileage: 585, // km per charge
    },
    safetyRating: 0.9,
    userReviews: 4.4,
  },
  {
    id: 15,
    make: "Toyota",
    model: "Fortuner",
    variant: "Legender 4x4",
    color: "Garnet Red",
    price: 4800000,
    specs: {
      engine: "2.8L Diesel",
      transmission: "Automatic",
      fuelType: "Diesel",
      seatingCapacity: 7,
      topSpeed: 190,
      mileage: 12.8,
    },
    safetyRating: 0.89,
    userReviews: 4.6,
  },
  {
    id: 16,
    make: "Honda",
    model: "Amaze",
    variant: "VX Elite",
    color: "Lunar Silver",
    price: 1050000,
    specs: {
      engine: "1.5L i-VTEC Petrol",
      transmission: "Manual",
      fuelType: "Petrol",
      seatingCapacity: 5,
      topSpeed: 185,
      mileage: 19.5,
    },
    safetyRating: 0.84,
    userReviews: 4.2,
  },
  {
    id: 17,
    make: "BMW",
    model: "5 Series",
    variant: "530i M Sport",
    color: "Sophisto Grey",
    price: 7200000,
    specs: {
      engine: "2.0L TwinPower Turbo",
      transmission: "Automatic",
      fuelType: "Petrol",
      seatingCapacity: 5,
      topSpeed: 250,
      mileage: 15.1,
    },
    safetyRating: 0.95,
    userReviews: 4.8,
  },
  {
    id: 18,
    make: "Maruti",
    model: "Baleno",
    variant: "Alpha AMT",
    color: "Nexa Blue",
    price: 920000,
    specs: {
      engine: "1.2L DualJet Petrol",
      transmission: "Automatic",
      fuelType: "Petrol",
      seatingCapacity: 5,
      topSpeed: 165,
      mileage: 22.9,
    },
    safetyRating: 0.79,
    userReviews: 4.1,
  },
  {
    id: 19,
    make: "Suzuki",
    model: "Grand Vitara",
    variant: "Alpha Hybrid",
    color: "Splendid Silver",
    price: 1850000,
    specs: {
      engine: "1.5L Strong Hybrid",
      transmission: "Automatic",
      fuelType: "Hybrid",
      seatingCapacity: 5,
      topSpeed: 180,
      mileage: 21.5,
    },
    safetyRating: 0.86,
    userReviews: 4.3,
  },
  {
    id: 20,
    make: "Volkswagen",
    model: "Taigun",
    variant: "GT 1.5 TSI",
    color: "Wild Cherry Red",
    price: 1750000,
    specs: {
      engine: "1.5L TSI Petrol",
      transmission: "Automatic",
      fuelType: "Petrol",
      seatingCapacity: 5,
      topSpeed: 200,
      mileage: 17.8,
    },
    safetyRating: 0.88,
    userReviews: 4.4,
  },
];
